<?php

return [
    /*
    |--------------------------------------------------------------------------
    | DISESBA - Información Corporativa
    |--------------------------------------------------------------------------
    */
    'company' => [
        'name' => 'DISESBA, S.A.',
        'tagline' => 'Distribuidora e Importadora de Medicamentos',
        'email' => 'informacion@disesba.com',
        'phone' => '(+505) 8440 7264',
        'phone_secondary' => '(+505) 8440 6341',
        'phone_raw' => '+50584407264',
        'phone_secondary_raw' => '+50584406341',
        'whatsapp_raw' => '50584407264',
        'location' => 'Managua, Nicaragua',
        'address' => 'Sede central en Managua, cobertura y distribución a nivel nacional.',
        'hours' => 'Lunes a Viernes: 8:00 AM - 5:00 PM | Sábados: 8:00 AM - 12:00 PM',
        'logo' => '/images/logodisesba.jpg',
    ],

    /*
    |--------------------------------------------------------------------------
    | Textos Corporativos Oficiales
    |--------------------------------------------------------------------------
    */
    'about' => [
        'title' => 'Quiénes Somos',
        'content' => 'En DISESBA, S.A., somos una distribuidora de medicamentos comprometida con brindar soluciones confiables y accesibles para el cuidado de la salud en Nicaragua. Con sede en Managua, trabajamos de la mano centros médicos para garantizar que los productos lleguen de manera segura, eficiente y oportuna a quienes más los necesitan. Nuestro compromiso está basado en la responsabilidad, la calidad y la confianza de nuestros clientes.',
    ],

    'mission' => [
        'title' => 'Nuestra Misión',
        'content' => 'Proveer medicamentos y productos farmacéuticos de alta calidad mediante una gestión eficiente de distribución, asegurando disponibilidad y accesibilidad para mejorar la salud y bienestar de la población nicaragüense.',
    ],

    'vision' => [
        'title' => 'Nuestra Visión',
        'content' => 'Ser la distribuidora de medicamentos líder en Nicaragua, reconocida por la excelencia en el servicio, la innovación en los procesos de distribución y el compromiso con la salud de la comunidad, consolidándonos como un socio estratégico de confianza en el sector farmacéutico.',
    ],

    'values' => [
        [
            'title' => 'Confianza',
            'description' => 'Relaciones sólidas y transparentes con centros médicos, farmacias e instituciones de salud en todo el territorio.',
            'icon' => 'shield-check',
        ],
        [
            'title' => 'Calidad',
            'description' => 'Fármacos elaborados bajo estrictos estándares farmacopeicos (USP/BP) y trazabilidad certificada.',
            'icon' => 'badge-check',
        ],
        [
            'title' => 'Distribución Segura',
            'description' => 'Cadena de custodia, conservación y entrega oportuna en Managua y todos los departamentos del país.',
            'icon' => 'truck',
        ],
        [
            'title' => 'Compromiso con la Salud',
            'description' => 'Dedicación continua a mejorar la disponibilidad y el acceso a tratamientos esenciales para la población.',
            'icon' => 'heart-pulse',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Catálogo de Productos Farmacéuticos con Información Ampliada Confirmada
    |--------------------------------------------------------------------------
    */
    'products' => [
        [
            'id' => 1,
            'slug' => 'omeprazol-20mg',
            'nombre' => 'Omeprazol',
            'concentracion' => '20 mg',
            'forma_farmaceutica' => 'Cápsulas USP',
            'presentacion' => '10 x 10 cápsulas',
            'categoria' => 'Gastrointestinal',
            'via' => 'Oral',
            'liberacion' => 'Liberación retardada',
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Omeprazol 20 mg en cápsulas USP de liberación retardada. Presentación comercial de 10 x 10 cápsulas, desarrollada para su administración oral y orientada al manejo de la acidez estomacal frecuente.',
            'caracteristicas' => [
                '20 mg',
                'Cápsulas USP',
                'Liberación retardada',
                'Presentación 10 x 10',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/omeprazol-20mg.jpg',
            'destacado' => true,
        ],
        [
            'id' => 2,
            'slug' => 'sildenafil-50mg',
            'nombre' => 'Sildenafil',
            'concentracion' => '50 mg',
            'forma_farmaceutica' => 'Tabletas USP',
            'presentacion' => '1 x 4 tabletas recubiertas',
            'categoria' => 'Salud masculina',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Sildenafil 50 mg en tabletas USP para administración oral. Se presenta en empaque de 1 x 4 tabletas con recubrimiento de película.',
            'caracteristicas' => [
                '50 mg',
                'Uso oral',
                'Tabletas USP',
                'Recubrimiento de película',
                'Presentación 1 x 4',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/sildenafil-50mg.jpg',
            'destacado' => false,
        ],
        [
            'id' => 3,
            'slug' => 'sildenafil-100mg',
            'nombre' => 'Sildenafil',
            'concentracion' => '100 mg',
            'forma_farmaceutica' => 'Tabletas USP',
            'presentacion' => '1 x 4 tabletas recubiertas',
            'categoria' => 'Salud masculina',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Sildenafil 100 mg en tabletas USP para administración oral. Presentación de 1 x 4 tabletas con recubrimiento de película.',
            'caracteristicas' => [
                '100 mg',
                'Uso oral',
                'Tabletas USP',
                'Recubrimiento de película',
                'Presentación 1 x 4',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/sildenafil-100mg.jpg',
            'destacado' => false,
        ],
        [
            'id' => 4,
            'slug' => 'ibuprofeno-400mg',
            'nombre' => 'Ibuprofeno',
            'concentracion' => '400 mg',
            'forma_farmaceutica' => 'Tabletas recubiertas BP',
            'presentacion' => '10 x 10 tabletas recubiertas',
            'categoria' => 'Analgésicos y antiinflamatorios',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Ibuprofeno 400 mg en tabletas recubiertas BP. Presentación comercial de 10 x 10 tabletas, clasificada dentro de la línea de productos analgésicos y antiinflamatorios.',
            'caracteristicas' => [
                '400 mg',
                'Analgésico',
                'Antiinflamatorio',
                'Tabletas recubiertas BP',
                'Presentación 10 x 10',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/ibuprofeno-400mg.jpg',
            'destacado' => true,
        ],
        [
            'id' => 5,
            'slug' => 'azithromycin-500mg',
            'nombre' => 'Azithromycin',
            'concentracion' => '500 mg',
            'forma_farmaceutica' => 'Tabletas USP',
            'presentacion' => '10 x 10 tabletas recubiertas',
            'categoria' => 'Antibióticos',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Azithromycin 500 mg en tabletas USP. Producto de la línea antibiótica y antibacterial presentado en formato de 10 x 10 tabletas recubiertas.',
            'caracteristicas' => [
                '500 mg',
                'Tabletas USP',
                'Antibiótico',
                'Antibacterial',
                'Presentación 10 x 10',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/azithromycin-500mg.jpg',
            'destacado' => true,
        ],
        [
            'id' => 6,
            'slug' => 'losartan-potasio-50mg',
            'nombre' => 'Losartan Potasio',
            'concentracion' => '50 mg',
            'forma_farmaceutica' => 'Tabletas recubiertas USP',
            'presentacion' => '10 x 10 tabletas recubiertas',
            'categoria' => 'Cardiovascular',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Losartan Potasio 50 mg en tabletas recubiertas USP para administración oral. Producto perteneciente a la línea cardiovascular, disponible en presentación de 10 x 10 tabletas.',
            'caracteristicas' => [
                '50 mg',
                'Vía oral',
                'Tabletas recubiertas USP',
                'Línea cardiovascular',
                'Presentación 10 x 10',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/losartan-potasio-50mg.jpg',
            'destacado' => true,
        ],
        [
            'id' => 7,
            'slug' => 'acetaminofen-100-tabletas',
            'nombre' => 'Acetaminofén',
            'concentracion' => '500 mg',
            'forma_farmaceutica' => 'Tabletas',
            'presentacion' => '100 tabletas',
            'categoria' => 'Analgésicos',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => null, // Confirmado: No indicar si no se confirma visualmente
            'descripcion' => 'Acetaminofén 500 mg en presentación comercial de 100 tabletas. Producto perteneciente a la categoría de analgésicos y disponible en una presentación de mayor cantidad de unidades.',
            'caracteristicas' => [
                '500 mg',
                'Tabletas',
                '100 unidades',
                'Presentación comercial',
            ],
            'imagen' => '/images/products/acetaminofen-100-tabletas-500mg.jpg',
            'destacado' => false,
        ],
        [
            'id' => 8,
            'slug' => 'amoxicilina-clavulanato-potasio-875-125mg',
            'nombre' => 'Amoxicilina y Clavulanato de Potasio',
            'concentracion' => '875/125 mg',
            'forma_farmaceutica' => 'Tabletas USP',
            'presentacion' => '3 x 7 tabletas',
            'categoria' => 'Antibióticos',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Combinación de Amoxicilina y Clavulanato de Potasio en concentración 875/125 mg, presentada en tabletas USP para administración oral. Presentación comercial de 3 x 7 tabletas.',
            'caracteristicas' => [
                'Amoxicilina 875 mg',
                'Clavulanato de Potasio 125 mg',
                'Tabletas USP',
                'Vía oral',
                'Presentación 3 x 7',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/amoxicilina-clavulanato-875-125mg.jpg',
            'destacado' => true,
        ],
        [
            'id' => 9,
            'slug' => 'amoxicilina-acido-clavulanico-875-125mg',
            'nombre' => 'Amoxicilina y Ácido Clavulánico',
            'concentracion' => '875 mg + 125 mg',
            'forma_farmaceutica' => 'Tabletas recubiertas',
            'presentacion' => '21 tabletas recubiertas',
            'categoria' => 'Antibióticos',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => null, // Confirmado: No indicar si no se confirma visualmente
            'descripcion' => 'Combinación de Amoxicilina 875 mg y Ácido Clavulánico 125 mg en tabletas recubiertas. Presentación comercial de 21 unidades.',
            'caracteristicas' => [
                'Amoxicilina 875 mg',
                'Ácido Clavulánico 125 mg',
                'Tabletas recubiertas',
                '21 unidades',
            ],
            'imagen' => '/images/products/amoxicilina-acido-clavulanico-875-125mg.jpg',
            'destacado' => false,
        ],
        [
            'id' => 10,
            'slug' => 'acetaminofen-10x10-tabletas',
            'nombre' => 'Acetaminofén',
            'concentracion' => '500 mg',
            'forma_farmaceutica' => 'Tabletas USP',
            'presentacion' => '10 x 10 tabletas',
            'categoria' => 'Analgésicos',
            'via' => 'Oral',
            'liberacion' => null,
            'laboratorio' => 'Alpha Galeno',
            'descripcion' => 'Acetaminofén 500 mg en tabletas USP para administración oral. Presentación de 10 x 10 tabletas, perteneciente a la línea de productos analgésicos y reductores de fiebre.',
            'caracteristicas' => [
                '500 mg',
                'Tabletas USP',
                'Vía oral',
                'Analgésico',
                'Reductor de fiebre',
                'Presentación 10 x 10',
                'Producto Alpha Galeno',
            ],
            'imagen' => '/images/products/acetaminofen-500mg.jpg',
            'destacado' => false,
        ],
    ],
];
